#!/bin/bash

echo "🚀 Configuração do Neon Database para História de Alagoas"
echo "==========================================================="
echo ""
echo "Siga os passos abaixo para configurar o Neon Database:"
echo ""
echo "1. 📝 Acesse: https://neon.tech"
echo "2. 🔐 Faça login ou crie uma conta gratuita"
echo "3. ➕ Clique em 'Create Project'"
echo "4. 📋 Configure o projeto:"
echo "   - Project Name: historia-de-alagoas"
echo "   - Database Name: historiadealagoas"
echo "   - PostgreSQL Version: 15 (recomendado)"
echo "   - Region: US East (Ohio) - us-east-2"
echo ""
echo "5. 🔗 Após criar, copie a Connection String que aparece"
echo "6. 📝 Cole a string de conexão no arquivo .env"
echo ""
echo "Exemplo da string de conexão:"
echo "postgresql://username:password@ep-xxx.us-east-2.aws.neon.tech/dbname?sslmode=require"
echo ""
echo "🎯 Depois execute os comandos:"
echo "   npx prisma db push"
echo "   npm run build"
echo "   npm start"
echo ""
echo "✅ Seu banco estará pronto para produção!"
